#!/usr/bin/env python
# coding=utf-8

# simple git update for asena pulling from core modules
import os
import sys

# check where we are and load default directory
if os.path.isdir("/usr/share/asena-framework"):
    if not os.path.isfile("asena"):
        os.chdir("/usr/share/asena-framework")
        sys.path.append("/usr/share/asena-framework")

import src.core.asenacore as core

# if we can't see our config then something didn't go good..
if not os.path.isfile("/etc/asena-framework/asena.config"):
    core.print_error("Cannot locate Asena Framework executable. Try running from the local directory.")
    core.print_error("If this does not work, please run the setup.py install file.")
    sys.exit()

try:
    # pull update asena from the core libraries
    core.update_asena()

# except keyboard interrupts
except KeyboardInterrupt:
    print("\n[!] Control-C detected. Exiting updating Asena Framework.")

# handle all other errors
except Exception as e:
    print("\n[!] Something went wrong. Printing the error: {0}".format(e))
